### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7

### ISSUE THREAD

**Issue by martinbe1io** [abashev/vfs-s3#71]
Hi, thx for this library, unfortunately I'm running into this error under openjdk 14 on Mac any hint?

```
[2020-09-20 17:20:19,500]-[Hotswap] INFO  io.be1.circular.filemanager.FileSystem - Starting Filesystem name=usercontent type=mac props={createpolicy=createandcopy, name=usercontent, rootdir=s3://circular-test.oc3.be1.io.ams3.digitaloceanspaces.com/usercontent/}
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at io.be1.circular.my-app//org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:39)
	at io.be1.circular.my-app//org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
	at io.be1.circular.my-app//org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109)
	at io.be1.circular.my-app//org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
	at io.be1.circular.my-app//org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
	at io.be1.circular.my-app//org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:207)
	at io.be1.circular.my-app//org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:105)
	at io.be1.circular.my-app//org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:83)
	at io.be1.circular.my-app//groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:340)
	at io.be1.circular.my-app//com.amazonaws.util.VersionInfoUtils.languageVersion(VersionInfoUtils.java:279)
	at io.be1.circular.my-app//com.amazonaws.util.VersionInfoUtils.groovyVersion(VersionInfoUtils.java:206)
	at io.be1.circular.my-app//com.amazonaws.util.VersionInfoUtils.getAdditionalJvmLanguages(VersionInfoUtils.java:190)
	at io.be1.circular.my-app//com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:159)
	at io.be1.circular.my-app//com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:137)
	at io.be1.circular.my-app//com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:100)
	at io.be1.circular.my-app//com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:70)
	at io.be1.circular.my-app//com.github.vfss3.S3FileSystemConfigBuilder.getClientConfiguration(S3FileSystemConfigBuilder.java:95)
	at io.be1.circular.my-app//com.github.vfss3.S3FileSystemOptions.getClientConfiguration(S3FileSystemOptions.java:83)
	at io.be1.circular.my-app//com.github.vfss3.S3FileProvider.doCreateFileSystem(S3FileProvider.java:60)
	at io.be1.circular.my-app//com.github.vfss3.CachingFileProvider.findFile(CachingFileProvider.java:121)
	at io.be1.circular.my-app//com.github.vfss3.CachingFileProvider.findFile(CachingFileProvider.java:91)
	at io.be1.circular.my-app//com.github.vfss3.S3FileProvider.findFile(S3FileProvider.java:26)
	at io.be1.circular.my-app//org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:711)
	at io.be1.circular.my-app//org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:648)
	at io.be1.circular.my-app//io.be1.circular.filemanager.FileSystem.startFileSystem(FileSystem.java:79)
	at io.be1.circular.my-app//io.be1.circular.filemanager.FileManager.startFileSystem(FileManager.java:1417)
	at io.be1.circular.my-app//io.be1.circular.filemanager.FileManager.lambda$configure$0(FileManager.java:2340)
	at io.be1.circular.my-app//org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
	at io.be1.circular.my-app//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at io.be1.circular.my-app//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at io.be1.circular.my-app//org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
	at io.be1.circular.my-app//org.jooby.Jooby.start(Jooby.java:2219)
	at io.be1.circular.my-app//org.jooby.Jooby.start(Jooby.java:2178)
	at io.be1.circular.my-app//org.jooby.Jooby.run(Jooby.java:2107)
	at io.be1.circular.my-app//io.be1.circular.App.main(App.java:624)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:444)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by abashev** [comment]
It is related to conflicts between Groovy and JDK 14. You need to update groovy inside your project - I tested with 3.0.5 and it works fine

**Comment by abashev** [comment]
@martinbe1io FYI I added support for DigitalOcean into the latest release.

**Comment by martinbe1io** [comment]
Thx
